# Generated by Django 3.0.5 on 2020-04-28 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=225)),
                ('meal_name', models.CharField(max_length=225)),
                ('servings', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=6)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
