# Generated by Django 3.0.5 on 2020-04-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('nutrition_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
