# Generated by Django 3.0.5 on 2020-04-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_log', '0003_auto_20200429_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutrition',
            name='user',
        ),
    ]
